### ISSUE TITLE
unable to build a given buildroot config

### ISSUE THREAD

**Issue by wucke13** [velentr/buildroot.nix#6]
I'm trying to build the config found in https://github.com/analogdevicesinc/buildroot/tree/e783aadccebad3413b3d60fcfe98a25eb395d839 (as that builds the userspace of https://github.com/analogdevicesinc/plutosdr-fw). Unfortunately, the build of the lockfile fails right-away:

```console
pluto-rootfs-packages.lock> Running phase: unpackPhase
pluto-rootfs-packages.lock> unpacking source archive /nix/store/sldryl829xixdjzff28kbd393kkhs76d-source/buildroot
pluto-rootfs-packages.lock> source root is buildroot
pluto-rootfs-packages.lock> Running phase: patchPhase
pluto-rootfs-packages.lock> Running phase: updateAutotoolsGnuConfigScriptsPhase
pluto-rootfs-packages.lock> Updating Autotools / GNU config script to a newer upstream version: ./support/gnuconfig/config.sub
pluto-rootfs-packages.lock> Updating Autotools / GNU config script to a newer upstream version: ./support/gnuconfig/config.guess
pluto-rootfs-packages.lock> Running phase: buildPhase
pluto-rootfs-packages.lock> Missing source libini-a467418 in checksums
pluto-rootfs-packages.lock> URLs: http://sources.buildroot.net/libini/libini-a467418-br1.tar.gz
pluto-rootfs-packages.lock> http://sources.buildroot.net/libini-a467418-br1.tar.gz
pluto-rootfs-packages.lock> Traceback (most recent call last):
pluto-rootfs-packages.lock>   File "/nix/store/63jy017pdk7x11cdk8ij69ny2xs5yn0f-make-package-lock.py", line 103, in <module>
pluto-rootfs-packages.lock>     main()
pluto-rootfs-packages.lock>   File "/nix/store/63jy017pdk7x11cdk8ij69ny2xs5yn0f-make-package-lock.py", line 94, in main
pluto-rootfs-packages.lock>     downloads_info = create_download_info(checksums_index, package_info)
pluto-rootfs-packages.lock>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pluto-rootfs-packages.lock>   File "/nix/store/63jy017pdk7x11cdk8ij69ny2xs5yn0f-make-package-lock.py", line 46, in create_download_info
pluto-rootfs-packages.lock>     raise Exception(f"Missing checksum for source {name}")
pluto-rootfs-packages.lock> Exception: Missing checksum for source libini-a467418
```

**Comment by velentr** [comment]
This can happen if there is a source tarball in buildroot that does not have a corresponding hash checked in to a `.hash` file. This is valid in buildroot, but nix requires a hash for all downloaded sources, so my `make-package-lock.py` will raise an error in this case.

To work around this, you can either add a corresponding `.hash` file to the buildroot repo or add `extraSha256Hashes` to the `mkBuildroot` invocation in your flake. Something like `extraSha256Hashes = { "libini-a467418-br1.tar.gz" = <sha256 of the downloaded file>;}`

**Comment by wucke13** [comment]
So I put

```nix
let
  buildrootPackages = buildroot-nix.lib.mkBuildroot {
    inherit pkgs;
    name = "pluto-rootfs";
    defconfig = "zynq_pluto_defconfig";
    lockfile = ./buildroot.lock;
    src =
      (pkgs.fetchFromGitHub {
        inherit (self.packages.${system}.pluto-image.src) owner repo rev;
        fetchSubmodules = true;
        hash = "sha256-MKlTUqtly7oINQg2rhoWejiILn8PWMoLNJUVg6G/prg=";
      })
      + "/buildroot";
    extraSha256Hashes = {
      "libini-a467418-br1.tar.gz" = "sha256-MKlTUqtly7oINQg2rhoWejiILn8PWMoLNJUVg3G/prg=";
      "libini-a467418" = "sha256-MKlTUqtly7oINQg2rhoWejiILn8PWMoLNJUVg3G/prg=";
    };
  };
in
buildrootPackages.packageLockFile;
```

but still I get the same error? Also, the URL is bogus, as in it returns 404. Also `libini-a467418-br1.tar.gz` does not match in the repo, so where is this URL coming from?

**Comment by wucke13** [comment]
Also, the package is probably hosted externally:

```
################################################################################
#
# libini
#
################################################################################

LIBINI_VERSION = a467418
LIBINI_SITE = https://github.com/pcercuei/libini.git
LIBINI_SITE_METHOD = git

LIBINI_INSTALL_STAGING = YES
LIBINI_LICENSE = LGPLv2.1+
LIBINI_LICENSE_FILES = LICENSE.txt

$(eval $(cmake-package))
```
